declare namespace NodeJS {
	interface ProcessEnv {
		EXPO_PUBLIC_BACKEND_API_URL: string;
		EXPO_PUBLIC_DEFAULT_COMMISSION_PERCENT: number;
		EXPO_PUBLIC_DEFAULT_DRAW_TIMES: number;
		EXPO_PUBLIC_DEFAULT_CACHE_TTL: number;
		EXPO_PUBLIC_VEXO_API_KEY: string;
	}
}
